# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc_
import warnings

import src.grpc_.services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc_.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComponentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.forward = channel.unary_unary(
                '/services.Component/forward',
                request_serializer=services__pb2.ComponentMessage.SerializeToString,
                response_deserializer=services__pb2.ComponentResponse.FromString,
                _registered_method=True)


class ComponentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc_.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComponentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'forward': grpc_.unary_unary_rpc_method_handler(
                    servicer.forward,
                    request_deserializer=services__pb2.ComponentMessage.FromString,
                    response_serializer=services__pb2.ComponentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc_.method_handlers_generic_handler(
            'services.Component', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.Component', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Component(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc_.experimental.unary_unary(
            request,
            target,
            '/services.Component/forward',
            services__pb2.ComponentMessage.SerializeToString,
            services__pb2.ComponentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
