services:
  offline-feeder:
    build:
      context: ../../
      dockerfile: deploy/offline_feeder/Dockerfile
    cap_add:
      - NET_ADMIN
    # network_mode: host
    shm_size: '1gb'
    depends_on:
      - base-torch
    ports:
      - "50054:50054"
    container_name: nids-offline-feeder
    image: localhost:42069/nids-offline-feeder:latest
