services:
  offline-feeder:
    build:
      context: ../../
      dockerfile: deploy/offline_feeder/Dockerfile
    cap_add:
      - NET_ADMIN
    # network_mode: host
    shm_size: '1gb'
    ports:
      - "50054:50054"
    image: offline-feeder
