stages:
  train_residual:
    cmd: >
      python src/ai/train.py
      --lr 0.0001
      --batch_size 256
      --constructor ResidualNetwork
      --all_data
    deps:
    - src/ai/train.py
    - data/CIC
    outs:
    - data/checkpoints/ResidualNetwork.ckpt
    metrics:
    - dvclive/metrics.json

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
