stages:
  train_residual:
    cmd: >
      python src/ai/train.py
      --lr 0.001
      --batch_size 128
      --early_stop_patience 10
      --ckpt_name ResidualSmall
      --constructor ResidualNetwork
    deps:
    - src/ai/train.py
    - data/CIC
    outs:
    - data/checkpoints/ResidualSmall.ckpt
    metrics:
    - dvclive/metrics.json

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
