metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
stages:
  train_residual:
    cmd: >
      python src/ai/train.py  --epochs 20
      --batch_size 256
      --constructor ResidualNetwork
      --all_data
    deps:
    - src/ai/train.py
    - data/CIC
    outs:
    - data/checkpoints/ResidualNetwork.ckpt
    metrics:
    - dvclive/metrics.json

  train_recurrent:
    cmd: >
      python src/ai/train.py  --epochs 10
      --batch_size 64
      --constructor RNN
      --all_data
    deps:
    - src/ai/train.py
    - data/CIC
    outs:
    - data/checkpoints/RNN.ckpt
    metrics:
    - dvclive/metrics.json
params:
- dvclive/params.yaml
