stages:
  train_residual:
    cmd: >
      python src/ai/train.py
      --lr 0.001
      --batch_size 128
      --early_stop_patience 10
      --constructor ResidualNetwork
      --all_data
    deps:
    - src/ai/train.py
    - data/CIC
    outs:
    - data/checkpoints/ResidualNetwork.ckpt
    metrics:
    - dvclive/metrics.json

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
