[tool.ruff]
line-length = 88
fix = true

exclude = [
    "src/grpc_",
    "src/ai",
    "tests"
]


[tool.ruff.lint]
per-file-ignores = {"src/services/feeder/feeder.py" = ["E501"], "sdk/services/example/main.py" = ["F401"]}
select = ["E4", "E7", "E9", "F", "B", "R", "C", "E", "W", "I"]
external = ["isort"]

unfixable = ["B"]
fixable = ["I"]
