[tool.ruff]
line-length = 88
# fix = true

exclude = [
    "src/grpc_",
    "src/ai",
    "tests"
]

[tool.ruff.lint]

# line too long warnings
per-file-ignores = { "src/services/feeder/feeder.py" = ["E501"] }
