services:
  logger:
    build:
      context: ../../
      dockerfile: deploy/logger/Dockerfile
      args:
        CACHE_FROM: ${REGISTRY}/nids-logger:latest
        REGISTRY: "${REGISTRY}"
    ports:
      - "50055:50055"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: nids-logger
    depends_on:
      mongo:
        condition: service_healthy
      mongo-express:
        condition: service_healthy
      python-base:
        condition: service_started
    profiles:
      - log
    attach: false # silence terminal output
    image: ${REGISTRY}/nids-logger:latest
