include:
  - neural_network/compose.yml
  - feeder/compose.yml
  - offline_feeder/compose.yml
  - logger/compose.yml
  # - store/compose.yml

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: python-base
  base-torch:
    build:
      context: .
      dockerfile: Dockerfile-torch.base
    depends_on:
      - base
    image: torch-base
