include:
  - neural_network/compose.yml
  - feeder/compose.yml
  - offline_feeder/compose.yml
  - logger/compose.yml
  # - store/compose.yml

services:
  python-base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        CACHE_FROM: ${REGISTRY}/python-base:latest
        REGISTRY: "${REGISTRY}"
    image: ${REGISTRY}/python-base:latest

  torch-base:
    build:
      context: .
      dockerfile: Dockerfile-torch.base
      args:
        CACHE_FROM: ${REGISTRY}/torch-base:latest
        REGISTRY: "${REGISTRY}"
    depends_on:
      - python-base
    image: ${REGISTRY}/torch-base:latest
