include:
  - model/compose.yml
  - feeder/compose.yml
  - offline_feeder/compose.yml
  # - logger/compose.yml
  - store/compose.yml
  - mongo/compose.yml

networks:
  default:
    name: components
