ARG _REGISTRY
FROM ${_REGISTRY}/python-base
LABEL org.opencontainers.image.source https://github.com/isaiahharvi/nids

RUN uv pip install --system --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu torch lightning scikit-learn numpy pandas
