services:
  residual:
    build:
      context: ../../
      dockerfile: deploy/model/Dockerfile
      args:
        - MODEL_PATH=data/checkpoints/ResidualNetwork.ckpt
        - FILE_NAME=residual.py
        - PORT=50052
    ports:
      - "50052:50052"
    image: residual
