services:
  neural-network:
    build:
      context: ../../
      dockerfile: deploy/model/Dockerfile
      args:
        - MODEL_PATH=data/checkpoints/ResidualSmall.ckpt
    ports:
      - "50052:50052"
    image: neural-network
