services:
  feeder:
    build:
      context: ../../
      dockerfile: deploy/feeder/Dockerfile
      args:
        CACHE_FROM: ${REGISTRY}/nids-feeder:latest
        REGISTRY: "${REGISTRY}"
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - torch-base
    ports:
      - "50053:50053"
    # environment:
    #   GRPC_VERBOSITY: ERROR
    #   GRPC_LOG_SEVERITY: ERROR
    container_name: nids-feeder
    image: ${REGISTRY}/nids-feeder:latest
