services:
  feeder:
    build:
      context: ../../
      dockerfile: deploy/feeder/Dockerfile
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - base-torch
    ports:
      - "50053:50053"
    # environment:
    #   GRPC_VERBOSITY: ERROR
    #   GRPC_LOG_SEVERITY: ERROR
    container_name: nids-feeder
