#!/usr/bin/env bash

# DO NOT EDIT THIS FILE.

# Duplicate this file under scripts/ and name it setup_git_personal.sh
# DO NOT COMMIT `setup_git_personal.sh` it should be ignored.

# Fill in the below with your own github information
git config --global user.email ""
git config --global user.name ""
