#!/usr/bin/env bash

# DO NOT EDIT THIS FILE.


# Fill in the below with your own github information
git config --global user.email ""
git config --global user.name ""

# Duplicate this file and name it setup_git_personal.sh
