services:
  store-file:
    build:
      context: ../../
      dockerfile: deploy/store/Dockerfile.to-file
    ports:
      - "50056:50056"
    container_name: store-file

  store-db: 
    build:
      context: ../../
      dockerfile: deploy/store/Dockerfile.to-db
    ports:
      - "50057:50057"
    container_name: store-db
