FROM python-base

ENV PORT=50056
ENV CSV_OUT_NAME="output.csv"
LABEL ENVS="CSV_OUT_NAME"

COPY deploy/store/requirements.txt /app/requirements.txt
RUN uv pip install --no-cache-dir -r /app/requirements.txt && rm /app/requirements.txt

WORKDIR /app
ENV PYTHONPATH=/app/src

COPY src/grpc_ /app/src/grpc_
COPY src/services/store/to_file.py /app/main.py

CMD ["uv", "run", "main.py"]
