FROM python:3.11-slim

# points to mongo service
ENV PORT=50057
ENV HOST="mongo" 
ENV TARGET_PORT=27017
LABEL ENVS="HOST,TARGET_PORT"

COPY deploy/store/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt && rm /app/requirements.txt 

WORKDIR /app
ENV PYTHONPATH=/app/src

COPY src/grpc_ /app/src/grpc_
COPY src/services/mongo/mongo.py /app/src/services/mongo/mongo.py
COPY src/services/store/to_db.py /app/main.py

CMD ["python", "main.py"]
