services:
  neural-network:
    build:
      context: ../../
      dockerfile: deploy/neural_network/Dockerfile
      args:
        # - MODEL_PATH=data/checkpoints/ResidualNetwork.ckpt
        - MODEL_PATH=data/checkpoints/MLP.ckpt
    depends_on:
      - base-torch
    ports:
      - "50052:50052"
    container_name: nids-neural-network
    image: localhost:42069/nids-ids:latest
